server:
  port: 8090
spring:
  application:
    name: ADMIN
  datasource:
    url: jdbc:mysql://localhost:3306/mytestdb?serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
    instance:
      prepreferIpAddress: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  eureka:
    enabled: true

