server:
  port: 1030
eureka:
  instance:
    hostname: EUREKA-03
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.2.123:1020/eureka/,http://192.168.2.123:1010/eureka/
spring:
  application:
    name: EUREKA-03
