server:
  port: 1010
eureka:
  instance:
    hostname: EUREKA-01
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
