server:
  port: 1010
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: EUREKA-01
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://EUREKA-02:1020/eureka/,http://EUREKA-03:1030/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: EUREKA-01
