server:
  port: 1020
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: EUREKA-02
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://EUREKA-01:1010/eureka/,http://EUREKA-03:1030/eureka/
spring:
  application:
    name: EUREKA-02
