server:
  port: 10200
spring:
  application:
    name: BLOG
  datasource:
    url: jdbc:mysql://localhost:3306/mytestdb?serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
    instance:
      prepreferIpAddress: true
ribbon:
  eureka:
    enabled: true

